### ISSUE TITLE
Add the ability to differentiate tests with their class name in Zebrunner

### ISSUE THREAD

**Issue by FredVaugeois** [zebrunner/community-edition#320]
Basically, our problem is that whenever we have an abstract test class (for example, if for 10 different test classes we need to test X, we create an abstract test class that tests X and our 10 classes will inherit from it), it is shown as the same test in Zebrunner. 

What this means is that it will log each and every test that has the same name as the same row in Zebrunner, which is not really the desired behavior. Zebrunner needs to have the ability to know that if it's a different class that tests this method, it should not be considered as exactly the same test.

**Comment by vdelendik** [comment]
closing as won't fix. that's might be an enhancement for [reporting](https://github.com/zebrunner/reporting).
generally, there are a lot of instruments to customize naming on test level: https://zebrunner.com/documentation/reporting/testng
