### ISSUE TITLE
provide possibility to launch setup process in debug mode

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/community-edition#328]
for future it would be great to have possibility to launch bash "setup" script in debug mode using single arg or property.
in output it supposed to have information about every bash command we execute

**Comment by vdelendik** [comment]
details: https://serverfault.com/questions/16204/how-to-make-bash-scripts-print-out-every-command-before-it-executes

**Comment by azarouski** [comment]
to check this issue try to launch 'setup' with '-d' argument
```bash
./zebrunner.sh setup -d
```

**Comment by vdelendik** [comment]
@dhreben, need to test using community-edition setup, branch: develop
