### ISSUE TITLE
There is ".disabled" present in minio-storage after setup all  components

### ISSUE THREAD

**Issue by dhreben** [zebrunner/community-edition#411]
**Test scenario:**

1.git clone --recurse-submodule --branch develop https://github.com/zebrunner/zebrunner.git
2.export REPORTING_DISABLED=1
3..`/zebrunner.sh setup `with disabled as much as possible components.
4.`./zebrunner.sh shutdown `
5.unset REPORTING_DISABLED
6.`./zebrunner.sh setup` with all enabling components
7. cd reporting/minio-storage/ 

 **Actual result :** There is ".disabled" present in minio-storage after setup all  components
 
<img width="732" alt="Screenshot 2021-02-12 at 17 38 07" src="https://user-images.githubusercontent.com/50950954/107781622-237f6300-6d59-11eb-979c-954e20f68878.png">

**Comment by vdelendik** [comment]
fixed running `reporting/minio/zebrunner.sh shutdown` from current zebrunner repo and its genereal zebrunner.sh script

**Comment by dhreben** [comment]
Fixed.

**Comment by dhreben** [comment]
After fix this https://github.com/zebrunner/zebrunner/issues/441 ticket reproduced  this issue.

Test scenario:

1.git clone --recurse-submodule --branch develop https://github.com/zebrunner/zebrunner.git
2.export REPORTING_DISABLED=1
3../zebrunner.sh setup with disabled as much as possible components.
4../zebrunner.sh shutdown 
5.unset REPORTING_DISABLED
6../zebrunner.sh setup with all enabling components
7. cd reporting/minio-storage/

Actual result : There is ".disabled" present in minio-storage after setup all components


<img width="484" alt="Screenshot 2021-04-02 at 16 18 22" src="https://user-images.githubusercontent.com/50950954/113418957-2698e600-93cf-11eb-96f3-1de7c5fd5338.png">

**Comment by vdelendik** [comment]
@dhreben this particular use case should be fixed
