### ISSUE TITLE
OnPush-carina demo  request doesn't work with Bitbucket

### ISSUE THREAD

**Issue by dhreben** [zebrunner/community-edition#420]
**Test scenario:**

1.Sign in Bitbucket
2.Migrate carina-demo project to Bitbucket
3.Open Jenkins
4.Run RegisterOrganization
5.Tap RegisterRepository

 - In scmType select Bitbucket
 - In repourl copy your carina-demo bitbucket HTTPS repository.

6.Run build
7. Open your terminal and run the following command `echo -n username:password | base64` where username and password are your BitBucket credentials, this will return a token encoded in base64.
8.Open BitBucket repository page with carina-demo
9.Tap Repository Settings
10.Tap Webhooks
11.Tap add webhook.
12.Enter http://your-zebrunner-domain.com/jenkins/generic-webhook-trigger/invoke?token=bitbucket-token-here into URL field.
13.Check that Repository push is selected.
14.Tap save
15.Open repository page with carina-demo
16.Tap Readmi.md
17.Tap edit
18.Make small changes e.g. put a dot
19.Tap Commit
19.Open jenkins
20.Open your Bitbucket organization
21.Tap Carina-demo
22.Check that  OnPush-carina-demo run new build.

**Actual result** : OnPush-carina demo  request doesn't work with Bitbucket.

**Comment by dhreben** [comment]
` java.util.MissingFormatArgumentException: Format specifier '%s'` after create RegisterRepository

**Comment by vdelendik** [comment]
@dhreben - make sure RegisterRepository has latest `develop` pipeline branch for Zebrunner-CE.
Based on the error it uses master or main...

**Comment by dhreben** [comment]
Fixed
