### ISSUE TITLE
upgrade: add appropriate warn that previous sonar will be terminated completely

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/community-edition#429]
CE v2.2 has sonarqube:7.9.4-community based sonar (originally on ubuntu linux).
in v2.3 we jumped to sonarqube:9.9.0-community which is on alpine.

In scope of this ticket we have to test if upgrade scenario is possible at all.
1. setup v2.2 from master
2. do repository registration 
-> double check that sonar static code analysis present
3. setup onPR and onPush events and execute them successfully
4. switch to the develop branch and pull recursively `git pull --recurse-submodules`
5. run `./zebrunner.sh upgrade` and restart everything
-> review sonarqube container logs. I suspect to see exceptions and as result inaccessible sonar
-> if sonar is available take a look to pre-upgrade analysis if it is available for user
6. register the same repo again 
-> double check if new analysis appear
7. test onPR and onPush events

**Comment by vdelendik** [comment]
closing as it is QA activities only

**Comment by okamara** [comment]
I got error during registration repo for onPush job:
12:59:33  [ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.8.0.2131:sonar (default-cli) on project carina-demo: Validation of project reactor failed:
12:59:33  [ERROR]   o To use the property "sonar.branch.name" and analyze branches, Developer Edition or above is required. See https://redirect.sonarsource.com/doc/branches.html for more information.
12:59:33  [ERROR] -> [Help 1]
12:59:33  [ERROR] 
12:59:33  [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
12:59:33  [ERROR] Re-run Maven using the -X switch to enable full debug logging.
12:59:33  [ERROR] 
12:59:33  [ERROR] For more information about the errors and possible solutions, please read the following articles:
12:59:33  [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[Pipeline] }

**Comment by vdelendik** [comment]
returned back to 2.1 as existing sonar has vulnerable log4j2x on board (imbedded elasticsearch)

**Comment by vdelendik** [comment]
@okamara, let's test again

**Comment by okamara** [comment]
Re-verified.
In step 5 run ./zebrunner.sh upgrade and restart everything
-> review sonarqube container logs. I suspect to see exceptions and as result inaccessible sonar
- Sonar can't start properly
<img width="1042" alt="Снимок экрана 2023-04-20 в 18 18 07" src="https://user-images.githubusercontent.com/32964663/233411665-1acd9e18-28ec-4ca3-b520-915970c66551.png">

**Comment by vdelendik** [comment]
due to the huge changes in between sonarqube versions we can't support normal upgrade. So, let's provide during the upgrade warning about destroyng previous sonar instance and data completely. And during upgrade stop sonarqube and destroy all 3 related docker volumes

**Comment by vdelendik** [comment]
it is part of the release docs already (in draft state): https://github.com/zebrunner/community-edition/releases/tag/untagged-555e9941203286abf894

```
Note: During upgrade we can't support migration of SonarQube module! It means all data will be destroyed and you must configure from scratch over 9.8.0 community edition of sonar!
```

**Comment by okamara** [comment]
verified. fixed.
