### ISSUE TITLE
Add correct link example for Webhook URL in Create a GitHub App

### ISSUE THREAD

**Issue by okamara** [zebrunner/community-edition#442]
Steps:
OPen https://zebrunner.github.io/zebrunner/config-guide/#register-repository
Scroll till Create a GitHub App

Change example link " For example, https://zebrunner.com/."  to "For example, http://your-zebrunner-domain.com/jenkins/generic-webhook-trigger/invoke?token=github-token-here"

<img width="723" alt="Снимок экрана 2021-04-09 в 17 25 52" src="https://user-images.githubusercontent.com/32964663/114194943-a9ceb480-9958-11eb-8583-2d3f212fcbb9.png">

**Comment by vdelendik** [comment]
closing as won't fix. existing example is valid for github app settings
