### ISSUE TITLE
provide extra information for restore operation

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/community-edition#455]
during `./zebrunner.sh restore` let's provide extra information about backup date of each sub-component.
For now we only warn that data might be lost. It will be useful to show backup generation date for each sub-component so administrator ensure he restore the system to that dates

**Comment by vdelendik** [comment]
fixed adding 2 modifications:
1. if you run `./zebrunner.sh restore` with backup you should see warning and exit:
```
You have to backup something in advance using: ./zebrunner.sh backup
For more help join telegram channel: https://t.me/zebrunner
```
2. when you already have a backup we show not datetime state when your backup was done and message should be:
```
Your services will be stopped and current data might be lost.
Do you want to do a restore to "Thu Jul 21 13:50:53 UTC 2022" state? y/n [n]:
```

where date is calculated based on backup/settings.env.bak file only

**Comment by okamara** [comment]
Verified, for case 2 I got old message, need fix.
<img width="645" alt="Снимок экрана 2022-07-28 в 19 25 18" src="https://user-images.githubusercontent.com/32964663/181589611-04ba6011-4d32-4ec4-b240-7c3a6301db43.png">

**Comment by okamara** [comment]
2 case was tested with wrong command, after re-verification with ./zebrunner.sh restore it works fine

**Comment by vdelendik** [comment]
closed based on latest comment
