### ISSUE TITLE
Add the ability to delete video on test success

### ISSUE THREAD

**Issue by FredVaugeois** [zebrunner/community-edition#468]
It would be great, to avoid having too much data, to have to ability to have a checkbox in Jenkins (that could be parametrized in the xml file of a Carina project) that would register videos, but delete them when the test has passed. 

It can be done manually by the user, but I always feel that it is a little bit risky to delete data that Zebrunner uses without knowing exactly how the data communicates in the Docker container.

**Comment by vdelendik** [comment]
[cleanup.zip](https://github.com/zebrunner/zebrunner/files/6825253/cleanup.zip)
let's review and provide ability to clean all kind of historical data

**Comment by vdelendik** [comment]
closing as won't fix because simple removal might be done manually. good one should include sync in reporting db which is not so simple...
