### ISSUE TITLE
remove protection via htpasswd files for embedded mcloud and selenoid

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/community-edition#481]
for CE version it was decided to remove htpasswd with `demo:demo` credentials at all.
Make sure in additions to the settings update review and clean documentation

**Comment by vdelendik** [comment]
done. right after CE setup from develop branch verify that 
1. selenoid and mcloud urls are accessible without any credentials:
http://hostname/mcloud/wd/hub
http://hostname/mcloud/grid/console
http://hostname/selenoid/wd/hub

**Comment by okamara** [comment]
verified on develop branch. Fixed.
