### ISSUE TITLE
reload nginx conf files every 6 hours

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/community-edition#485]
```
command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
```

**Comment by vdelendik** [comment]
done. setup CE from develop, launch services and execute regression and wait for 6h+
-> everything should be good, all components accessible through web.
adjust any nginx.conf introducing mistake in any location, /sonarqube or similar and wait for 6h+
-> everything should work except sonarqube. make sure to corrupt redirect and not a syntax

**Comment by okamara** [comment]
Tested, Need reverify sonar in 6 hours.

**Comment by okamara** [comment]
Re-verified in 7 hours. Fixed.
<img width="1226" alt="Снимок экрана 2022-07-26 в 21 32 14" src="https://user-images.githubusercontent.com/32964663/181084645-084ab985-4ac3-45ae-8087-30385f89d818.png">
<img width="1440" alt="Снимок экрана 2022-07-26 в 21 31 03" src="https://user-images.githubusercontent.com/32964663/181084660-83c8025a-5d36-4ceb-9959-63c60e933f87.png">
