### ISSUE TITLE
move upgrade/patch steps onto the each sub-component

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/community-edition#491]
As we started support of independent sub-component setup we have to reorganize upgrade process and make it fully independent as well on each sub-component level.

Exact requirements still TBD

**Comment by vdelendik** [comment]
done for jenkins-master, mcloud and selenoid.
it is organized via executing `./zebrunner.sh setup` on every sub-module level automatically and regenerating required files automatically. due to the presence of CE installer all these steps should be done automatically which is guarantee the same process for every upgrade.
Also for all above sub-module some allowed customizations in variables.env and/or .env should be preserved

**Comment by vdelendik** [comment]
to test follow regular upgrade checklist with minor adjustments:
1. setup CE using master branch (2.0 release in master branch)
2. do basic acceptance
3. inject some customizations into the:
```
jenkins-master/variables.env //inject user token insted of password for admin
mcloud/variables.env //specify valid STF_TOKEN and maybe SECRET
selenoid/.env //CPU or MEMORY
```
4. restart and do basic again to verify that infra is ok
5. switch to the develop branch and pull sub-modules recursively 
```
git checkout develop
git pull --recurse-submodules
```
6. run `./zebrunner.sh upgrade`, confirm action and services restart
-> all custom settings in variables.env/.env files should be preserved
7. do again basic acceptance to see that new selenoid, pipeline 1.8 version in jenkins and 2.2 STF are good enough

**Comment by okamara** [comment]
Verified fixed. Created a separate issue for VNC session.
