### ISSUE TITLE
aws marketplace: update usage instructions

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/community-edition#494]
1. remove details about links in matkertplace
2. provide link to the `Configuration Guide` directly
3. Put into the head of the config guide common information about urls for jenkins, stf, sonar etc
4. add run job example and report analysis review step righ tafter the RegisterRepository call
-> think about using default build job as not everybody use carina
5. webhooks and sonar configuration made optional in the doc (maybe move onto the dedicated page)

**Comment by vdelendik** [comment]
done steps 3-5. need to find aws guide to fix 1-2 and close the ticket completely

**Comment by vdelendik** [comment]
fixed aws marketplace guide as well

**Comment by okamara** [comment]
verified, fixed.
