### ISSUE TITLE
unable to source utility.sh when launch zebrunner.sh from different folder

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/community-edition#499]
/home/build/tools/zebrunner/mcloud/zebrunner.sh: line 4: patch/utility.sh: No such file or directory

**Comment by vdelendik** [comment]
fixed. to test I can recommend to 
1. clone as usual into tools or home
2. change current dir, for example `cd /tmp`
3. start setup using `/home/built/tools/community-edition/zebrunner.sh setup`
4. complete setup and start
-> no more error message like in subj and everything is configured and started successfully

**Comment by okamara** [comment]
verified on develop branch, fixed.
