### ISSUE TITLE
log4j vulnerability issue in eleasticsearch and logstash docker container in zebrunner CE

### ISSUE THREAD

**Issue by jdpower1337** [zebrunner/community-edition#500]
Zebrunner CE 1.9

The following containers use a vulnerable version of log4j (2.11.1 & 2.13.3) 

-elasticsearch
-logstash

We need a fix to be able to update the above docker container so it has a version of log4j without the vulnerability.

**Comment by jdpower1337** [comment]
Hello there guys! I know that you are really busy but is there any development on that issue or any "plan" is the update of the reporting service 1.26.2 gonna be a definitive fix?

**Comment by vdelendik** [comment]
@jdpower1337, waiting for oss version of elatsicseach. logstash-oss seems available in rc
https://github.com/zebrunner/reporting/issues/2335

**Comment by vdelendik** [comment]
request resolved in https://github.com/zebrunner/reporting/issues/2335. latest reporting is part of the CE in develop and should be tested. ETA - Jan, 28.

**Comment by okamara** [comment]
Verified, fixed.
