### ISSUE TITLE
400 error after opening https://demo.zebrunner.farm

### ISSUE THREAD

**Issue by dhreben** [zebrunner/community-edition#501]
Steps:

1../zebrunner.sh setup
2. Enter https
3. Enter 443 port
4. Open https://demo.zebrunner.farm:443

Actual result: 400 error after opening  https://demo.zebrunner.farm:443

**Comment by vdelendik** [comment]
fixed. it should be tested pulling latest changes from develop branch in this community-edition repo.

**Comment by dhreben** [comment]
Fixed
