### ISSUE TITLE
What's the limitation of Zebrunner CE version.

### ISSUE THREAD

**Issue by swordligit** [zebrunner/community-edition#502]
I am finding an open-source test management tools, and guided by this
link
https://theqalead.com/tools/best-open-source-test-management-tools/
I find the Zebrunner is cool, but from Zebrunner's main page, it seems
it is priced.
So I want know what the limitation of Zebrunner CE version? is there a
side by side description of CE version and priced version?
Br,
SwordLi

**Comment by vdelendik** [comment]
@swordligit, the biggest difference between CE and PRO is that 1st one is hosted on your own on-premise hardware, 2nd one in cloud as SaaS solution.
Also feature list differs a little bit, more information you can find below:
![image](https://user-images.githubusercontent.com/4551455/149939059-cf3e810e-9b9a-44c5-bc84-9009138f1d27.png)
