### ISSUE TITLE
404 error after redirection to Zebrunner MCloud 

### ISSUE THREAD

**Issue by dhreben** [zebrunner/community-edition#503]
**Test scenario:**

1. Open https://www.qps-infra.io/
2. Click 'Read more'  on mobile cloud

**Actual result**: 404 error after redirection to Zebrunner MCloud 

**Expected  result** :  Link redirection to  https://zebrunner.com/products/mobile-testing-farm/ 

![Screenshot 2022-01-17 at 12 06 58](https://user-images.githubusercontent.com/50950954/149740100-08a26cc2-e1aa-456e-95bf-7d9e10b62679.png)

**Comment by vdelendik** [comment]
closing as won't fix because qps-infra.io is going to be destroyed: https://github.com/zebrunner/community-edition/issues/513

**Comment by dhreben** [comment]
Won't fix. Closed
