### ISSUE TITLE
automate upgrade steps to 2.0

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/community-edition#506]
analyze changes and organize upgrade script.
CE: https://github.com/zebrunner/community-edition/pull/505/files
DONE:  nginx/conf.d/default.conf.original

jenkins: https://github.com/zebrunner/jenkins-master/pull/365/files - add pipeline version update as readme step!
variables.env.original

mcloud: https://github.com/zebrunner/mcloud/pull/121/files
.env.original
configuration/stf-proxy/nginx.conf.original
variables.env.original

reporting: https://github.com/zebrunner/reporting/pull/2337/files
DONE: .env.original

selenoid: https://github.com/zebrunner/selenoid/pull/38/files
DONE: .env.original

sonarqube: N/A

**Comment by vdelendik** [comment]
done. @okamara, please move to `Done` if it is successfully tested on your side.

**Comment by okamara** [comment]
Verified, fixed.
