### ISSUE TITLE
review all public repos and replace 1.10 -> 2.0 for CE release notes

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/community-edition#508]
we decided to name 1.10 as 2.0 so all previously released repos aka mcloud, jenkins, etc should be ajusted to have 2.0 as well in their release notes

**Comment by vdelendik** [comment]
such release notes updated:
https://github.com/zebrunner/mcloud-agent/releases/tag/2.0
https://github.com/zebrunner/jenkins-master/releases/tag/1.8
https://github.com/zebrunner/mcloud/releases/tag/2.0
https://github.com/zebrunner/mcloud-grid/releases/tag/2.0
https://github.com/zebrunner/reporting/releases/tag/1.27

**Comment by okamara** [comment]
Verified, fixed.
