### ISSUE TITLE
Errors in upgrade scenario during git pull operation 

### ISSUE THREAD

**Issue by okamara** [zebrunner/community-edition#509]
Steps:
1. git clone --recurse-submodule https://github.com/zebrunner/zebrunner.git
2. ./zebrunner.sh setup
3. Create organization (pipeline version - 1.6), Register Repo
4. git checkout develop
5. git pull --recurse-submodules
Actual result: error messages are present ->
"Fetching submodule jenkins
Fetching submodule mcloud
Fetching submodule reporting
Fetching submodule reporting/minio-storage
Fetching submodule selenoid
Fetching submodule sonarqube
Already up to date.
Submodule path 'jenkins': checked out '36270e63ee20fec9717590d10b67f63eefef00cc'
error: unable to create file configuration/stf-proxy/ssl/.gitkeep: Permission denied
error: unable to create file configuration/stf-proxy/ssl/ssl.crt: Permission denied
error: unable to create file configuration/stf-proxy/ssl/ssl.key: Permission denied"
Expected result: git pull --recurse-submodules operation worked without errors

Note: upgrade works with errors 
SOURCE_VERSION: 1.9
Upgrading Zebrunner from 1.9 to 2.0
cp: cannot stat 'mcloud/configuration/stf-proxy/nginx.conf': No such file or directory
Upgrade to 2.0 finished successfully

**Comment by vdelendik** [comment]
added step 3 in release notes about steps to fix

**Comment by okamara** [comment]
verified, fixed.
