### ISSUE TITLE
No such file "nginx.conf" during run upgrade operation

### ISSUE THREAD

**Issue by okamara** [zebrunner/community-edition#510]
Steps:
1. 
git clone --recurse-submodule https://github.com/zebrunner/zebrunner.git
2. ./zebrunner.sh setup
3. Create organization (pipeline version - 1.6), Register Repo
4. git checkout develop
5. git pull --recurse-submodules
6. ls -la mcloud/configuration/stf-proxy/ssl
chown -R ubuntu:ubuntu mcloud/configuration/stf-proxy/ssl
-> make sure to use your actual user and group name!
7. Run upgrade
Actual result: error messages are present ->

Upgrading Zebrunner from 1.9 to 2.0
cp: cannot stat 'mcloud/configuration/stf-proxy/nginx.conf': No such file or directory

**Comment by vdelendik** [comment]
fixed. in comparison with 1.9 this particular file was removed so when we pulled recursively we removed it from the disk.
so fix include removal of extra backup generation and creating this file from original from scratch

**Comment by okamara** [comment]
verified, fixed.
