### ISSUE TITLE
provide detailed install guide

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/community-edition#515]
let's describe in details setup process to provide more understanding what all these settings mean

**Comment by vdelendik** [comment]
done: https://zebrunner.github.io/community-edition/install-guide/
it has now all setup steps with details including sample run. please, verify all links as well

**Comment by okamara** [comment]
need remove duplicate text 
https://zebrunner.github.io/community-edition/install-guide/
<img width="635" alt="Снимок экрана 2022-02-14 в 18 30 31" src="https://user-images.githubusercontent.com/32964663/153894083-8eb10d00-ee13-4b84-9a9c-170ae415e6cc.png">

**Comment by vdelendik** [comment]
@okamara, fixed all 3 mistakes

**Comment by okamara** [comment]
Verified, fixed.
need to fix also "staic" to "static" 
https://zebrunner.github.io/community-edition/integration/scm/
<img width="693" alt="Снимок экрана 2022-02-16 в 13 11 56" src="https://user-images.githubusercontent.com/32964663/154243664-6ddb311f-c50f-44ac-bbc0-32e7d80e5cb8.png">

**Comment by vdelendik** [comment]
@okamara, fixed `staic` to `static` in https://zebrunner.github.io/community-edition/integration/scm/
