### ISSUE TITLE
Add correct links in doc 

### ISSUE THREAD

**Issue by okamara** [zebrunner/community-edition#522]
Steps:
1. Open https://zebrunner.github.io/community-edition doc
2. Click Mcloud link is -> it is redirected to https://zebrunner.com/
Expected: https://zebrunner.com/mcloud
3. Click on [Zebrunner Engine](https://zebrunner.com/)
Expected: it should redirected to Zebrunner Selenium Grid page

**Comment by vdelendik** [comment]
@okamara, fixed. as we don't have yet selenium grid separate page I updated only name of the link and keep redirecting to zebtunner.com. new ticket will submit to adjust when we have child page

**Comment by okamara** [comment]
Verified, fixed.
