### ISSUE TITLE
2.1 upgrade steps

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/community-edition#525]
MCloud:
https://github.com/zebrunner/mcloud/pull/146
https://github.com/zebrunner/mcloud/pull/132

.env.original
variables.env.original
docker-compose.yml

Jenkins:
https://github.com/zebrunner/jenkins-master/pull/371
variables.env.original

Selenoid:
https://github.com/zebrunner/selenoid/pull/42
.env.original

**Comment by vdelendik** [comment]
done as part of #491. all testing steps are described there as well.

**Comment by okamara** [comment]
Testing is done for Mcloud and Jenkins. Selenoid need to reverify after fix the bug https://github.com/zebrunner/selenoid/issues/44

**Comment by vdelendik** [comment]
closed per verification in #491
