### ISSUE TITLE
docs: update links and branch names

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/community-edition#547]
scan all docs md and reuse final naming for the org/repo. also let's change develop to master or main when merge `2.3 rc` PR: https://github.com/zebrunner/community-edition/pull/542

**Comment by vdelendik** [comment]
done. @okamara - visit https://zebrunner.github.io/community-edition/ doc site and verify that:
1. all pictures are displayed
2. all links works fine
pay attention to the references to the github repositories etc

**Comment by okamara** [comment]
Wrong links on page for Zebrunner Reporting, Jenkins
<img width="1258" alt="Снимок экрана 2023-04-28 в 18 27 17" src="https://user-images.githubusercontent.com/32964663/235190610-36e063a1-0484-43e6-967d-840c12c35801.png">
<img width="387" alt="Снимок экрана 2023-04-28 в 18 25 41" src="https://user-images.githubusercontent.com/32964663/235190634-4c8ae00b-b9ca-4fb8-a4d2-3d1fdc1e50ab.png">

<img width="586" alt="Снимок экрана 2023-04-28 в 18 29 29" src="https://user-images.githubusercontent.com/32964663/235190572-074e6fe5-7fb8-4bd4-bffc-b9c87aa99142.png">

**Comment by okamara** [comment]
verified, fixed.
