### ISSUE TITLE
upgrade: automate required changes

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/community-edition#549]
registerHubCredentials: zebrunner/jenkins-master#368
new SONAR_TOKEN env var: zebrunner/jenkins-master#388

**Comment by vdelendik** [comment]
done: all management jobs after upgrade should be re-created. to verify it open every job via `Configure` and confirm that `main` branch is used for the pipeline library:
```
@Library('Zebrunner-CE@main')
```

also verify that new env var SONAR_TOKEN is present. If not, submit new ticket with `documentation` label as it might be manual step.

**Comment by okamara** [comment]
Verified, after upgrade Register Organization still contains master.
Created separate ticket about this.
