### ISSUE TITLE
implement 2.5 patch upgrade script

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/community-edition#576]
subj

**Comment by vdelendik** [comment]
done. upgrade scenario better to test to make sure we correctly upgrade mcloud, reporting and jenkins.
for jenkins pay attention to the plugins, it shouldn't corrupt plugins anymore on upgrade

**Comment by dhreben** [comment]
Basic acceptance  with iOS-Preferences-Test ,Mobile-iOS-Safari-Test ,  Android-Demo-Test  successfully completed. Video, screenshots and logs are available.
Also verified jenkins upgrade from 2.1 ->2.2version without corrupt plugins
