### ISSUE TITLE
Test Execution history section doesn't include the current run

### ISSUE THREAD

**Issue by maximusunc** [zebrunner/community-edition#584]
When I click on a specific test and it shows me the test execution history, it shows all past runs but the current one.
![Screenshot 2024-01-23 at 3 40 45 PM](https://github.com/zebrunner/community-edition/assets/29668529/a27328f6-94a5-4d8c-8592-1a38bd13a0c4)

If I click on one of the past runs, it takes me to that run, but then I can't easily get back to the current one, as there is no button to go back.
![Screenshot 2024-01-23 at 3 42 14 PM](https://github.com/zebrunner/community-edition/assets/29668529/0968a6f9-4f9a-4bb9-8aa0-eb08249ad270)

**Comment by vdelendik** [comment]
it should be fixed already
